{
  "openapi": "3.0.0",
  "info": {
    "title": "Digest",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://{{baseurl}}"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "Org"
    },
    {
      "name": "Org > Team"
    },
    {
      "name": "Org > Auth"
    },
    {
      "name": "Org > Metrics"
    },
    {
      "name": "Org > Categories"
    },
    {
      "name": "Org > Ingredients"
    },
    {
      "name": "Org > Dishes"
    },
    {
      "name": "Org > Recipes"
    },
    {
      "name": "Org > Onboarding"
    },
    {
      "name": "Customer"
    },
    {
      "name": "Customer > Auth"
    }
  ],
  "paths": {
    "/org/team": {
      "get": {
        "tags": ["Org > Team"],
        "summary": "All Team members",
        "operationId": "allTeamMembers",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 11 Apr 2024 04:24:28 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "502"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "data": [
                    {
                      "id": "81c7e4a4-19cf-48a7-bd02-f07fd239e8c4",
                      "first_name": "Joseph",
                      "password": "$argon2id$v=19$m=19456,t=2,p=1$4KmqjtSTFuUANlxHA+4Zxg$RXVfFWxe3Md4ZxtdMaz/lWRwsF9eM1eoWzgOerynlPM",
                      "last_name": "Owonvwon",
                      "email": "joseph.owonwo@gmail.com",
                      "role": "OWNER",
                      "created_at": "2024-04-11T01:52:52.330Z",
                      "updated_at": null,
                      "deleted_at": null
                    }
                  ],
                  "meta": {
                    "current_page": 1,
                    "per_page": 25,
                    "total": 1
                  }
                }
              }
            }
          }
        }
      }
    },
    "/org/team/c718b157-4fe4-4bb1-adc4-787e95b239a2": {
      "delete": {
        "tags": ["Org > Team"],
        "summary": "Delete Team member",
        "operationId": "deleteTeamMember",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/org/auth/login": {
      "post": {
        "tags": ["Org > Auth"],
        "summary": "Login - Org",
        "operationId": "loginOrg",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "joseph.owonwo@gmail.com",
                  "password": "helloman"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Mon, 08 Apr 2024 03:18:00 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "158"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Login successful",
                  "data": {
                    "access_token": "6wfgh44amvxok4twm08v7cimg5k3065ay1oklioh",
                    "expires": "2024-05-08T03:18:00.035Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/org/auth/logout": {
      "post": {
        "tags": ["Org > Auth"],
        "summary": "Logout - Org",
        "operationId": "logoutOrg",
        "requestBody": {
          "content": {}
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 10 Apr 2024 01:38:00 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "37"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Session terminated"
                }
              }
            }
          }
        }
      }
    },
    "/org/profile": {
      "get": {
        "tags": ["Org > Auth"],
        "summary": "Profile",
        "operationId": "profile",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "tags": ["Org > Metrics"],
        "summary": "Get Metrics",
        "operationId": "getMetrics",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/kpi/customers": {
      "get": {
        "tags": ["Org > Metrics"],
        "summary": "Customer Growth Metrics",
        "operationId": "customerGrowthMetrics",
        "parameters": [
          {
            "name": "range",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "1wk, 1mth, 1y, all. default: 1mth",
            "example": "1mth"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/categories/meals": {
      "post": {
        "tags": ["Org > Categories"],
        "summary": "Create a Meal Category",
        "operationId": "createAMealCategory",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Pastries"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": ["Org > Categories"],
        "summary": "Get all categories",
        "operationId": "getAllCategories",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/categories/05fa9976-2366-479b-8854-21727fb78152": {
      "delete": {
        "tags": ["Org > Categories"],
        "summary": "Delete Category",
        "operationId": "deleteCategory",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/ingredients": {
      "get": {
        "tags": ["Org > Ingredients"],
        "summary": "Get Ingredients",
        "operationId": "getIngredients",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "12"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": ["Org > Ingredients"],
        "summary": "Create Measurement",
        "operationId": "createMeasurement",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Vanilla Extract"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/dishes": {
      "post": {
        "tags": ["Org > Dishes"],
        "summary": "Create Meal",
        "operationId": "createMeal",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Peppered snail and crab shell",
                  "description": "{{$randomLoremParagraph}}",
                  "status": "DRAFT",
                  "category": [4],
                  "updated_at": "{{$isoTimestamp}}",
                  "created_at": "{{$isoTimestamp}}",
                  "video_url": "https://youtube.com/watch?q=ve9320a"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": ["Org > Dishes"],
        "summary": "Get Meals",
        "operationId": "getMeals",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/recipes": {
      "post": {
        "tags": ["Org > Recipes"],
        "summary": "Create a Recipe",
        "operationId": "createARecipe",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "meal_id": "ee6b9c6d-6241-4feb-b70e-7bf6f7b798f6",
                  "serving": 2,
                  "cooking_time": 120,
                  "ingredients": [
                    {
                      "measurement_id": 1,
                      "ingredient_id": 1,
                      "quantity": 0.5
                    }
                  ],
                  "steps": [
                    {
                      "order": 1,
                      "image": "{{$randomImageUrl}}",
                      "caption": "Dance a little",
                      "paragraph": "{{$randomLoremParagraph}}"
                    },
                    {
                      "order": 2,
                      "image": "{{$randomImageUrl}}",
                      "caption": "Dance a little",
                      "paragraph": "{{$randomLoremParagraph}}"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 27 Mar 2024 21:39:42 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "251"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Recipe created",
                  "data": {
                    "serial": 8,
                    "id": "1b7356e7-de71-4fa0-9ea1-13766dd2b49b",
                    "serving": 2,
                    "cooking_time": 120,
                    "created_at": "2024-03-27T21:39:35.732Z",
                    "updated_at": "2024-03-27T21:39:35.732Z"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Org > Recipes"],
        "summary": "All Recipes",
        "operationId": "allRecipes",
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 27 Mar 2024 21:39:42 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "251"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "example-0": {
                    "summary": "Success",
                    "value": {
                      "message": "Recipe created",
                      "data": {
                        "serial": 8,
                        "id": "1b7356e7-de71-4fa0-9ea1-13766dd2b49b",
                        "serving": 2,
                        "cooking_time": 120,
                        "created_at": "2024-03-27T21:39:35.732Z",
                        "updated_at": "2024-03-27T21:39:35.732Z"
                      }
                    }
                  },
                  "example-1": {
                    "summary": "Success",
                    "value": {
                      "data": [
                        {
                          "serial": 8,
                          "id": "1b7356e7-de71-4fa0-9ea1-13766dd2b49b",
                          "serving": 2,
                          "cooking_time": 120,
                          "created_at": "2024-03-27T21:39:35.732Z",
                          "updated_at": "2024-03-27T21:39:35.732Z",
                          "meals": [
                            {
                              "serial": 2,
                              "id": "ee6b9c6d-6241-4feb-b70e-7bf6f7b798f6",
                              "name": "Ghana Jollof",
                              "description": "Dicta aliquid corporis nobis hic qui et officia quas quis. Quo omnis dolor modi maxime facere corrupti minima aliquid recusandae. Illo reiciendis officia officiis tenetur eos sit ratione sit. Amet earum amet iure at quia.",
                              "status": "DRAFT",
                              "created_at": "2024-03-25T04:51:18.624Z",
                              "updated_at": "2024-03-25T04:51:18.624Z",
                              "video_url": "https://youtube.com/watch?q=ve9320a"
                            }
                          ]
                        },
                        {
                          "serial": 4,
                          "id": "2e6d3f86-01ed-46d0-aa03-f977658c1223",
                          "serving": 2,
                          "cooking_time": 120,
                          "created_at": "2024-03-27T19:41:30.693Z",
                          "updated_at": "2024-03-27T19:41:30.693Z",
                          "meals": [
                            {
                              "serial": 2,
                              "id": "ee6b9c6d-6241-4feb-b70e-7bf6f7b798f6",
                              "name": "Ghana Jollof",
                              "description": "Dicta aliquid corporis nobis hic qui et officia quas quis. Quo omnis dolor modi maxime facere corrupti minima aliquid recusandae. Illo reiciendis officia officiis tenetur eos sit ratione sit. Amet earum amet iure at quia.",
                              "status": "DRAFT",
                              "created_at": "2024-03-25T04:51:18.624Z",
                              "updated_at": "2024-03-25T04:51:18.624Z",
                              "video_url": "https://youtube.com/watch?q=ve9320a"
                            }
                          ]
                        }
                      ],
                      "meta": {
                        "current_page": 2,
                        "per_page": 2,
                        "total": 7
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/recipes/{recipeId}": {
      "get": {
        "tags": ["Org > Recipes"],
        "summary": "Get A Recipe",
        "operationId": "getARecipe",
        "parameters": [
          {
            "name": "recipeId",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 27 Mar 2024 23:23:11 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "1849"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "data": {
                    "serial": 1,
                    "id": "70b0543c-de4c-445e-a6c2-131f5c5c0aa7",
                    "serving": 2,
                    "cooking_time": 120,
                    "created_at": "2024-03-27T19:33:59.883Z",
                    "updated_at": "2024-03-27T19:33:59.883Z",
                    "meals": [
                      {
                        "serial": 2,
                        "id": "ee6b9c6d-6241-4feb-b70e-7bf6f7b798f6",
                        "name": "Ghana Jollof",
                        "description": "Dicta aliquid corporis nobis hic qui et officia quas quis. Quo omnis dolor modi maxime facere corrupti minima aliquid recusandae. Illo reiciendis officia officiis tenetur eos sit ratione sit. Amet earum amet iure at quia.",
                        "status": "DRAFT",
                        "created_at": "2024-03-25T04:51:18.624Z",
                        "updated_at": "2024-03-25T04:51:18.624Z",
                        "video_url": "https://youtube.com/watch?q=ve9320a"
                      }
                    ],
                    "recipes": [
                      {
                        "serial": 1,
                        "id": "61f32a50-175d-4bcf-b3e4-2c4b49f65599",
                        "image": "http://placeimg.com/640/480",
                        "order": 1,
                        "caption": "Dance a little",
                        "paragraph": "Laudantium enim consequatur enim animi voluptatem quaerat nemo. Consequuntur illum quae exercitationem ducimus molestiae quae soluta hic aut. Natus sit doloremque et itaque et non. Perspiciatis voluptates placeat. Vel ullam est quam ut et.",
                        "recipeId": "70b0543c-de4c-445e-a6c2-131f5c5c0aa7"
                      },
                      {
                        "serial": 2,
                        "id": "374965ef-0ad8-448f-9f40-a88bccef233f",
                        "image": "http://placeimg.com/640/480",
                        "order": 2,
                        "caption": "Dance a little",
                        "paragraph": "Repellat consectetur molestias eum velit ab reprehenderit aliquid dicta ipsam. Dicta et magni minus quaerat eius sed reiciendis. Qui dolores iure. Exercitationem iste velit. A velit accusamus qui quis qui placeat at molestiae.",
                        "recipeId": "70b0543c-de4c-445e-a6c2-131f5c5c0aa7"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/org/onboarding/questions": {
      "get": {
        "tags": ["Org > Onboarding"],
        "summary": "Get Questions",
        "operationId": "getQuestions",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "access-control-allow-origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 21 Apr 2024 00:01:07 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "5528"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "data": [
                    {
                      "id": "5eac4875-cd28-4b4a-b0ce-60e1a5be512f",
                      "type": "single",
                      "text": "Are you diabetic?",
                      "status": "DRAFT",
                      "options": [
                        {
                          "id": "79a9b597-935c-4ead-9b07-588a433d7a5c",
                          "text": "Yes",
                          "image": null,
                          "questionId": "5eac4875-cd28-4b4a-b0ce-60e1a5be512f"
                        },
                        {
                          "id": "578856a8-9686-4006-be8f-f6a7e3929d55",
                          "text": "No",
                          "image": null,
                          "questionId": "5eac4875-cd28-4b4a-b0ce-60e1a5be512f"
                        }
                      ]
                    },
                    {
                      "id": "672d0022-898b-4d8d-9da0-3e2d6d734dd7",
                      "type": "multiple",
                      "text": "Do you have any allergy?",
                      "status": "PUBLISHED",
                      "options": [
                        {
                          "id": "55cb1a83-5564-4259-bf6f-565d46f24134",
                          "text": "Sea food",
                          "image": null,
                          "questionId": "672d0022-898b-4d8d-9da0-3e2d6d734dd7"
                        },
                        {
                          "id": "0ca5884a-6e05-41d8-ac35-3e2f280f9247",
                          "text": "Fish",
                          "image": null,
                          "questionId": "672d0022-898b-4d8d-9da0-3e2d6d734dd7"
                        },
                        {
                          "id": "f6e00c82-e532-4a75-a094-80aac1fb59ea",
                          "text": "Egg",
                          "image": null,
                          "questionId": "672d0022-898b-4d8d-9da0-3e2d6d734dd7"
                        },
                        {
                          "id": "ccb3bc30-74cd-482a-8a21-7a14b701d37a",
                          "text": "Peanut",
                          "image": null,
                          "questionId": "672d0022-898b-4d8d-9da0-3e2d6d734dd7"
                        },
                        {
                          "id": "0d593271-6c9e-4ba9-86a5-6e6c1107b2fc",
                          "text": "Celery",
                          "image": null,
                          "questionId": "672d0022-898b-4d8d-9da0-3e2d6d734dd7"
                        }
                      ]
                    },
                    {
                      "id": "45751715-c5eb-4dc2-ba66-ac07135d6ada",
                      "type": "single",
                      "text": "What your favourite window",
                      "status": "PUBLISHED",
                      "options": [
                        {
                          "id": "1b81cf10-50e6-48d8-8e41-6d2049a3b3d5",
                          "text": "Yes",
                          "image": null,
                          "questionId": "45751715-c5eb-4dc2-ba66-ac07135d6ada"
                        }
                      ]
                    },
                    {
                      "id": "a08dd432-6df8-470e-8812-c02d9d64004f",
                      "type": "multiple",
                      "text": "What your favourite window",
                      "status": "PUBLISHED",
                      "options": [
                        {
                          "id": "b6318183-ed2c-489c-a1d3-d9974d0ee2e8",
                          "text": "Yes",
                          "image": null,
                          "questionId": "a08dd432-6df8-470e-8812-c02d9d64004f"
                        },
                        {
                          "id": "f42de010-d4bc-4215-95a2-2db19205ab00",
                          "text": "No",
                          "image": null,
                          "questionId": "a08dd432-6df8-470e-8812-c02d9d64004f"
                        }
                      ]
                    },
                    {
                      "id": "f02dddd0-cecc-41be-9d36-ad70707466ae",
                      "type": "multiple",
                      "text": "What your favourite window",
                      "status": "PUBLISHED",
                      "options": [
                        {
                          "id": "0298390a-b033-4373-b52a-8b745b627539",
                          "text": "Yes",
                          "image": null,
                          "questionId": "f02dddd0-cecc-41be-9d36-ad70707466ae"
                        },
                        {
                          "id": "c584ee6c-13f3-4d50-b320-5cca87208798",
                          "text": "No",
                          "image": null,
                          "questionId": "f02dddd0-cecc-41be-9d36-ad70707466ae"
                        }
                      ]
                    },
                    {
                      "id": "e3b86580-438d-4602-bb14-705378b9e7ed",
                      "type": "multiple",
                      "text": "What your favourite window",
                      "status": "PUBLISHED",
                      "options": [
                        {
                          "id": "d013e070-6a3f-454d-aa1f-37ef9d2e4c0d",
                          "text": "Yes",
                          "image": null,
                          "questionId": "e3b86580-438d-4602-bb14-705378b9e7ed"
                        },
                        {
                          "id": "6183dfe0-1983-4ce2-86e1-9e0f848b5e01",
                          "text": "No",
                          "image": null,
                          "questionId": "e3b86580-438d-4602-bb14-705378b9e7ed"
                        }
                      ]
                    },
                    {
                      "id": "81540fd5-d97c-4225-b314-fb9980d58ba2",
                      "type": "multiple",
                      "text": "What your favourite fruit?",
                      "status": "PUBLISHED",
                      "options": [
                        {
                          "id": "d0578505-1696-4d0a-8e3d-52435ed15599",
                          "text": "Yes",
                          "image": null,
                          "questionId": "81540fd5-d97c-4225-b314-fb9980d58ba2"
                        },
                        {
                          "id": "9dbd0ee6-772f-404a-9f6b-1d125caf225e",
                          "text": "No",
                          "image": null,
                          "questionId": "81540fd5-d97c-4225-b314-fb9980d58ba2"
                        }
                      ]
                    },
                    {
                      "id": "5155935f-52ec-4eaf-855c-ff2e4d39926a",
                      "type": "multiple",
                      "text": "What your favourite fruit?",
                      "status": "PUBLISHED",
                      "options": [
                        {
                          "id": "7cb2f0f3-19af-4e78-9ffa-b14e31512b64",
                          "text": "Apple",
                          "image": null,
                          "questionId": "5155935f-52ec-4eaf-855c-ff2e4d39926a"
                        },
                        {
                          "id": "fbfb609c-f281-4425-89cd-bcbb758e7a18",
                          "text": "Orange",
                          "image": null,
                          "questionId": "5155935f-52ec-4eaf-855c-ff2e4d39926a"
                        }
                      ]
                    },
                    {
                      "id": "309f687d-0253-4dfa-863d-fd08b6a45487",
                      "type": "multiple",
                      "text": "What your favourite fruit?",
                      "status": "UNPUBLISHED",
                      "options": [
                        {
                          "id": "d82f60a2-9d6b-4aca-9b5d-97e7fb3f1627",
                          "text": "Apple",
                          "image": null,
                          "questionId": "309f687d-0253-4dfa-863d-fd08b6a45487"
                        },
                        {
                          "id": "fef2b37f-addf-4bb8-904f-c9bac1d672ae",
                          "text": "Orange",
                          "image": null,
                          "questionId": "309f687d-0253-4dfa-863d-fd08b6a45487"
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Org > Onboarding"],
        "summary": "Create Question",
        "operationId": "createQuestion",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "question": "What your favourite fruit?",
                  "status": "UNPUBLISHED",
                  "type": "multiple",
                  "options": [
                    {
                      "text": "Apple"
                    },
                    {
                      "text": "Orange"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "access-control-allow-origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 21 Apr 2024 00:00:40 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "196"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Question created",
                  "data": {
                    "id": "309f687d-0253-4dfa-863d-fd08b6a45487",
                    "type": "multiple",
                    "text": "What your favourite fruit?",
                    "status": "UNPUBLISHED"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/org/onboarding/questions/{questionId}": {
      "post": {
        "tags": ["Org > Onboarding"],
        "summary": "Update Question",
        "operationId": "updateQuestion",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "question": "Do you like beans?",
                  "status": "UNPUBLISHED",
                  "type": "single",
                  "options": [
                    {
                      "id": "60a1204d-c985-4ed7-b731-adf8491a518e",
                      "text": "Honey"
                    },
                    {
                      "id": "98c17408-938a-420f-ab43-6611130ec9b1",
                      "text": "Iron"
                    }
                  ]
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "questionId",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "access-control-allow-origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 21 Apr 2024 00:00:40 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "196"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "example-0": {
                    "summary": "Success",
                    "value": {
                      "message": "Question created",
                      "data": {
                        "id": "309f687d-0253-4dfa-863d-fd08b6a45487",
                        "type": "multiple",
                        "text": "What your favourite fruit?",
                        "status": "UNPUBLISHED"
                      }
                    }
                  },
                  "example-1": {
                    "summary": "Success",
                    "value": {
                      "message": "Update successful",
                      "data": {
                        "id": "5d827e40-e7f8-4750-8ffc-4f18f9a4c07f",
                        "type": "single",
                        "text": "Do you like beans?",
                        "status": "UNPUBLISHED",
                        "options": [
                          {
                            "id": "60a1204d-c985-4ed7-b731-adf8491a518e",
                            "text": "Honey",
                            "image": null,
                            "questionId": "5d827e40-e7f8-4750-8ffc-4f18f9a4c07f"
                          },
                          {
                            "id": "98c17408-938a-420f-ab43-6611130ec9b1",
                            "text": "Iron",
                            "image": null,
                            "questionId": "5d827e40-e7f8-4750-8ffc-4f18f9a4c07f"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": ["Org"],
        "summary": "Get Users",
        "operationId": "getUsers",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "12"
          },
          {
            "name": "range_created_at",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "[toDate,fromDate]"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/payments": {
      "get": {
        "tags": ["Org"],
        "summary": "Payments",
        "operationId": "payments",
        "parameters": [
          {
            "name": "user_id",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "(optional)",
            "example": "{{$randomUUID}}"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Customer > Auth"],
        "summary": "Login",
        "operationId": "login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "owonwo@live.com",
                  "password": "helloman"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Mon, 08 Apr 2024 03:18:00 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "158"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Login successful",
                  "data": {
                    "access_token": "6wfgh44amvxok4twm08v7cimg5k3065ay1oklioh",
                    "expires": "2024-05-08T03:18:00.035Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Customer > Auth"],
        "summary": "Logout",
        "operationId": "logout",
        "requestBody": {
          "content": {}
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "content-type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 10 Apr 2024 01:38:00 GMT"
                }
              },
              "connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "content-length": {
                "schema": {
                  "type": "integer",
                  "example": "37"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Session terminated"
                }
              }
            }
          }
        }
      }
    },
    "/onboarding/questions": {
      "get": {
        "tags": ["Customer"],
        "summary": "Onboarding Questions",
        "operationId": "onboardingQuestions",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}
